### ISSUE TITLE
Starter Templates のコードを Glitch に貼り付けてもエラーが出てしまいます

### ISSUE THREAD

**Issue by notsuka09** [Orphe-OSS/ORPHE-CORE.js#1]
![image](https://user-images.githubusercontent.com/109795819/180414479-47f35455-ea20-4f9e-b0ee-c1947b8b6a17.png)

**Comment by TetsuakiBaba** [comment]
ORPHE-Core.jsの読み込みに失敗しているようです。404を返しているので、jsdeliverのレスポンスfailが原因だと思います。時間を開けて何度かリロード等してみてください。
